### ISSUE TITLE
Rails 4.2.0 assoc typecast is broken

### ISSUE THREAD

**Issue by shlima** [exAspArk/filter_form#9]
Filter input with the association is broken now: 

```
 filter_input f, :user, in: :select2, predicate: :eq_any_or_nil
```

Raises `NoMethodError at /users undefined method `type' for nil:NilClass` Error

Instead of that I have to rewrite all inputs based on the regular input like this: 

```
 f.input :user_id_eq_any_or_nil, collection: User.default_order, in: :select2
```

**Comment by exAspArk** [comment]
@shlima, thanks for the issue :+1: 
I've fixed it in version `0.8.4`, could you please try it?
